Made command line parsing more robust.
Now fgn-backup refuses to run if any non-option command line
argument is given.

diff --git a/fgn-backup.in b/fgn-backup.in
--- a/fgn-backup.in
+++ b/fgn-backup.in
@@ -48,6 +48,8 @@ while getopts "VhiImMSstTfFcC" option; do
     esac
 done
 shift $(($OPTIND - 1))
+test $# -eq 0 || \
+    { echo "error: non-option command line arguments given"; exit 1; }
 
 # assure that there is only one instance of fgn-backup running
 mkdir -p "$BACKUPRUNDIR"
