ftp-upload: Check for errors during FTP session
Use a temporary logfile to check for transient (4??) and
permanent (5??) error messages.

diff --git a/ftp-upload.in b/ftp-upload.in
--- a/ftp-upload.in
+++ b/ftp-upload.in
@@ -23,11 +23,17 @@ ftp_upload()
 {
     test -x $(which ftp) || { echo "ERROR: could not find ftp" ; return 1 ; }
 
+    local ftplog=$(mktemp /tmp/ftplog.$$.XXXXXXXXXX)
+    trap "rm -f $ftplog" 0 1 5 15
+    # failure to create a temporary ftp log file is not fatal
+    test -n "$ftplog" && test -r "$ftplog" ||
+        echo "ERROR: could not create temporary ftp log file"
+
     cd ${BACKUPCACHEDIR}
     printf "Starting FTP transfer: "
     date
 
-    ftp -inv <<-BACKUPENDE
+    ftp -inv <<-BACKUPENDE | tee -- "$ftplog"
         open ${FTP_SERVER}
         user ${FTP_USER} ${FTP_PASS}
         bin
@@ -39,6 +45,8 @@ ftp_upload()
     test 0 -ne $? && printf '\n*** ftp process returned an error ***\n\n'
     printf "Finished FTP transfer: "
     date
+    grep -qE -- '^[45][0-9]{2} ' "$ftplog" &&
+        printf '\n*** there were errors during the FTP session ***\n\n'
 }
 
 # vim:filetype=sh:shiftwidth=4:expandtab:
