ftp-upload: Don't place ftp process inside if
Instead, check the exit code of the ftp process and
emit a message if this is not 0.

The exit code of ftp does not change if (transient?)
errors occured. Thus this check is not that important
for the errors we want to diagnose,

diff --git a/ftp-upload.in b/ftp-upload.in
--- a/ftp-upload.in
+++ b/ftp-upload.in
@@ -27,20 +27,17 @@ ftp_upload()
     printf "Starting FTP transfer: "
     date
 
-    if  ftp -inv <<-BACKUPENDE
-	open ${FTP_SERVER}
-	user ${FTP_USER} ${FTP_PASS}
-	bin
-	mkdir ${FTPDIR}
-	cd ${FTPDIR}
-	pwd
-	mput *
-	BACKUPENDE
-    then
-            printf "Finished FTP transfer: "
-    else
-            printf "Failed FTP transfer: "
-    fi
+    ftp -inv <<-BACKUPENDE
+        open ${FTP_SERVER}
+        user ${FTP_USER} ${FTP_PASS}
+        bin
+        mkdir ${FTPDIR}
+        cd ${FTPDIR}
+        pwd
+        mput *
+        BACKUPENDE
+    test 0 -ne $? && printf '\n*** ftp process returned an error ***\n\n'
+    printf "Finished FTP transfer: "
     date
 }
 
